name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        node: ['12']
    name: Git tag and Changelogs generation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --silent --prefer-offline

      - name: Execute Semantic Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/lughino/squash-merge.git
          git config user.email squash-merge-bot@gmail.com
          git config user.name squash-merge-bot
          yarn lerna version --yes
          git push origin main && git push --tags
